const ACTION_TYPES = {
    TOAST_ALERT: {
        OPEN_TOAST: 'OPEN_TOAST',
        CLEAR_TOAST: 'CLEAR_TOAST'
    },
    PAGE_TITLE_CHANGED: 'PAGE_TITLE_CHANGED',
    LOADING: 'LOADING_PROGRESS',
};

export {ACTION_TYPES}